Repository The-Monitor-Dev/The-Monitor-FE, pull requests merged in 2024-11, with the labels that each got.

#29 [Feature/#28] 사이드 메뉴 컴포넌트
  src/App.tsx
  src/assets/images/index.tsx
  src/assets/images/tmp.png
  src/assets/svg/analyze.svg
  src/assets/svg/index.tsx
  src/assets/svg/news.svg
  src/components/SideMenu/index.tsx
  src/constants/routes.ts
  src/pages/FindPassword/components/PasswordSentModal/index.tsx
  src/pages/Monitoring/index.tsx
  src/pages/Report/index.tsx
  src/pages/Setting/index.tsx
  src/router.tsx
Labels: Feat 🩵, Refactor ♻️

#25 [Feature/#24] 고객사 정보 추가 모달 구현
  src/assets/svg/addCircleThin.svg
  src/assets/svg/arrowBeforeThick.svg
  src/assets/svg/attention.svg
  src/assets/svg/close.svg
  src/assets/svg/index.tsx
  src/pages/Dashboard/components/AddModal/Step1/index.tsx
  src/pages/Dashboard/components/AddModal/Step2/index.tsx
  src/pages/Dashboard/components/AddModal/Step3/index.tsx
  src/pages/Dashboard/components/AddModal/index.tsx
  src/pages/Dashboard/components/EditModal/index.tsx
  src/pages/Dashboard/index.tsx
  src/pages/FindPassword/components/PasswordSentModal/index.tsx
  src/pages/FindPassword/index.tsx
  src/pages/SignUp/components/Step1/index.tsx
  src/pages/SignUp/components/Step2/index.tsx
  src/pages/SignUp/index.tsx
Labels: Add ✨, Feat 🩵

#31 [Feature/#30] 모니터링 페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/assets/svg/arrowDown.svg
  src/assets/svg/bookmarkBlank.svg
  src/assets/svg/bookmarkFill.svg
  src/assets/svg/clock.svg
  src/assets/svg/hamburger.svg
  src/assets/svg/index.tsx
  src/assets/svg/internet.svg
  src/assets/svg/profile.svg
  src/assets/svg/reportCheck.svg
  src/components/Header/index.tsx
  src/components/SideMenu/index.tsx
  src/pages/Monitoring/components/DateSelector/index.tsx
  src/pages/Monitoring/components/PortalDropdown/index.tsx
  src/pages/Monitoring/index.tsx
  src/pages/SignUp/index.tsx
Labels: Chore 🧹, Feat 🩵, Refactor ♻️

#34 [Feature/#33] 고객사 수정 모달 퍼블리싱 및 기타 모달 퍼블리싱
  src/App.tsx
  src/assets/svg/checkboxFill.svg
  src/assets/svgs/addCircleFill.svg
  src/assets/svgs/addCircleThin.svg
  src/assets/svgs/analyze.svg
  src/assets/svgs/arrowBeforeThick.svg
  src/assets/svgs/arrowDown.svg
  src/assets/svgs/attention.svg
  src/assets/svgs/bookmarkBlank.svg
  src/assets/svgs/bookmarkFill.svg
  src/assets/svgs/checkboxBlank.svg
  src/assets/svgs/checkboxError.svg
  src/assets/svgs/checkboxFill.svg
  src/assets/svgs/clock.svg
  src/assets/svgs/close.svg
  src/assets/svgs/delete.svg
  src/assets/svgs/editSquare.svg
  src/assets/svgs/error.svg
  src/assets/svgs/hamburger.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/internet.svg
  src/assets/svgs/loading.svg
  src/assets/svgs/logo.svg
  src/assets/svgs/moreHoriz.svg
  src/assets/svgs/news.svg
  src/assets/svgs/person.svg
  src/assets/svgs/profile.svg
  src/assets/svgs/reportCheck.svg
  src/assets/svgs/search.svg
  src/assets/svgs/visibilityOff.svg
  src/assets/svgs/visibilityOn.svg
  src/components/CancelModal/index.tsx
  src/components/Header/index.tsx
  src/components/Input/index.tsx
  src/components/SideMenu/index.tsx
  src/pages/Dashboard/components/AddModal/Step1/index.tsx
  src/pages/Dashboard/components/AddModal/Step2/index.tsx
  src/pages/Dashboard/components/AddModal/Step3/index.tsx
  src/pages/Dashboard/components/AddModal/index.tsx
  src/pages/Dashboard/components/DeleteModal/index.tsx
  src/pages/Dashboard/components/EditModal/index.tsx
  src/pages/Dashboard/index.tsx
  src/pages/FindPassword/components/PasswordSentModal/index.tsx
  src/pages/FindPassword/index.tsx
  src/pages/Monitoring/components/DateSelector/index.tsx
  src/pages/Monitoring/components/PortalDropdown/index.tsx
  src/pages/Monitoring/index.tsx
  src/pages/SignUp/components/Step1/PasswordCondition.tsx
  src/pages/SignUp/components/Step1/index.tsx
Labels: Feat 🩵

#37 [style/#36] 대시보드 페이지 스타일 수정
  src/pages/Dashboard/index.tsx
Labels: Style 💄

#39 [Refactor/#38] 리뷰 피드백 반영 및 모니터링 페이지 수정
  package.json
  src/api/axiosInstance.ts
  src/assets/svgs/logo.svg
  src/components/Header/index.tsx
  src/components/Input/index.tsx
  src/constants/routes.ts
  src/pages/FindPassword/index.tsx
  src/pages/Monitoring/components/DateSelector/index.tsx
  src/pages/Monitoring/components/PortalDropdown/index.tsx
  src/pages/Monitoring/index.tsx
  src/pages/SignUp/components/Step1/index.tsx
  src/pages/SignUp/components/Step2/index.tsx
Labels: Feat ✨, Refactor ♻️, Style 💄

#41 [Feature/#35] 보고서 편집 페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/assets/svgs/add.svg
  src/assets/svgs/arrowUp.svg
  src/assets/svgs/checkCircleFill.svg
  src/assets/svgs/checkCircleOutline.svg
  src/assets/svgs/delete.svg
  src/assets/svgs/doner.svg
  src/assets/svgs/handle.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/mail.svg
  src/assets/svgs/report.svg
  src/assets/svgs/summarize.svg
  src/assets/svgs/undo.svg
  src/components/Button/index.tsx
  src/components/Header/index.tsx
  src/constants/routes.ts
  src/pages/Dashboard/index.tsx
  src/pages/Monitoring/index.tsx
  src/pages/ReportEdit/components/AddNews/index.tsx
  src/pages/ReportEdit/components/DonerMenu/index.tsx
  src/pages/ReportEdit/components/SummarizeModal/index.tsx
  src/pages/ReportEdit/components/Table/SortableItem.tsx
  src/pages/ReportEdit/components/Table/index.tsx
  src/pages/ReportEdit/index.tsx
  src/router.tsx
Labels: Add 🌱, Chore 🧹, Feat ✨, Refactor ♻️, Style 💄

#44 [Feature/#43] 404 페이지
  src/assets/svgs/index.tsx
  src/assets/svgs/notFound.svg
  src/components/Button/index.tsx
  src/pages/NotFound/index.tsx
  src/router.tsx
Labels: Add 🌱, Feat ✨

#46 [Feature/#45] 보고서 관리 페이지 퍼블리싱
  src/assets/svgs/editNote.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/search.svg
  src/components/SearchBar/index.tsx
  src/pages/Dashboard/index.tsx
  src/pages/Report/index.tsx
Labels: Add 🌱, Feat ✨, Refactor ♻️

#48 [Feature/#47] 메일 전송 모달
  src/pages/ReportEdit/components/SendEmailModal/index.tsx
  src/pages/ReportEdit/components/SummarizeModal/index.tsx
  src/pages/ReportEdit/index.tsx
Labels: Feat ✨

#50 [Feature/#49] 보고서 편집 페이지 퍼블리싱
  package-lock.json
  package.json
  src/components/Dropdown/index.tsx
  src/constants/routes.ts
  src/features/report/DonerMenu/index.tsx
  src/features/report/ReportHeader/index.tsx
  src/features/report/ReportSection/index.tsx
  src/features/report/ReportTables/index.tsx
  src/features/report/SendEmailModal/index.tsx
  src/features/report/SummarizeModal/index.tsx
  src/features/report/Table/SortableItem.tsx
  src/features/report/Table/index.tsx
  src/pages/Monitoring/index.tsx
  src/pages/Report/index.tsx
  src/pages/ReportEdit/index.tsx
  src/pages/ReportNew/components/AddNews/index.tsx
  src/pages/ReportNew/index.tsx
  src/router.tsx
  tsconfig.app.json
Labels: Add 🌱, Feat ✨, Refactor ♻️

#51 [Refactor/#40] 대시보드 페이지 리팩토링
  src/components/KeywordInput/index.tsx
  src/pages/Dashboard/components/AddModal/Step1/index.tsx
  src/pages/Dashboard/components/AddModal/Step2/index.tsx
  src/pages/Dashboard/components/AddModal/Step3/index.tsx
  src/pages/Dashboard/components/AddModal/index.tsx
  src/pages/Dashboard/components/MonitoringCard/index.tsx
  src/pages/Dashboard/index.tsx
Labels: Feat ✨, Refactor ♻️

#54 [Feature/#53] 고객사 없을 때 페이지 퍼블리싱
  src/assets/images/dashboard.webp
  src/assets/images/index.tsx
  src/assets/svgs/addCircleFill.svg
  src/pages/Dashboard/components/ClientNotFound/index.tsx
  src/pages/Dashboard/index.tsx
  tailwind.config.js
Labels: Add 🌱, Feat ✨

#56 [Feature/#42] 모니터링, 보고서 api 연결
  package-lock.json
  package.json
  src/api/accountsAPI.ts
  src/api/apiUtils.ts
  src/api/articlesAPI.ts
  src/api/clients.ts
  src/api/hooks/accounts/useCheckToken.ts
  src/api/hooks/articles/useGetArticles.ts
  src/api/hooks/articles/useGetArticlesByKeyword.ts
  src/api/hooks/clients/useGetClientInfo.ts
  src/api/hooks/keywords/useGetKeywords.ts
  src/api/hooks/reports/useDeleteReport.ts
  src/api/hooks/reports/useGetReportDetails.ts
  src/api/hooks/reports/useGetReports.ts
  src/api/hooks/reports/usePatchReportColor.ts
  src/api/hooks/reports/usePatchReportTitle.ts
  src/api/hooks/reports/usePostSearchReports.ts
  src/api/keywordsAPI.ts
  src/api/reportsAPI.ts
  src/api/tokenInstance.ts
  src/api/types/articles.ts
  src/api/types/clients.ts
  src/api/types/reports.ts
  src/assets/images/index.tsx
  src/assets/images/tmp.png
  src/assets/svgs/arrowLeft.svg
  src/assets/svgs/arrowRight.svg
  src/assets/svgs/doubleArrowLeft.svg
  src/assets/svgs/doubleArrowRight.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/pencil.svg
  src/components/CancelModal/index.tsx
  src/components/Dropdown/index.tsx
  src/components/SearchBar/index.tsx
  src/components/SideMenu/index.tsx
  src/constants/category.ts
  src/features/report/ReportSection/index.tsx
  src/pages/Dashboard/components/AddModal/Step2/index.tsx
  src/pages/Dashboard/index.tsx
  src/pages/FindPassword/index.tsx
  src/pages/Monitoring/components/ArticleBox/index.tsx
  src/pages/Monitoring/components/Category/index.tsx
  src/pages/Monitoring/components/Pagination/index.tsx
  src/pages/Monitoring/index.tsx
  src/pages/Report/ReportBox/index.tsx
  src/pages/Report/index.tsx
  src/pages/ReportEdit/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/components/Step1/index.tsx
  src/pages/SignUp/components/Step2/index.tsx
  src/router.tsx
  src/types/category.ts
  src/utils/convertUtcToKst.ts
  tsconfig.app.json
Labels: Feat ✨, Refactor ♻️, Style 💄

#58 [Feature/#55] 모니터링 설정 페이지 퍼블리싱
  src/components/KeywordInput/index.tsx
  src/hooks/useValidateEmail.ts
  src/pages/Dashboard/components/AddModal/Step1/index.tsx
  src/pages/Dashboard/components/AddModal/Step2/index.tsx
  src/pages/Dashboard/components/AddModal/Step3/index.tsx
  src/pages/Dashboard/components/KeywordLabel/index.tsx
  src/pages/Setting/KeywordList/index.tsx
  src/pages/Setting/index.tsx
Labels: Feat ✨, Refactor ♻️

#62 [Feature/#57] 보고서 관리 api 연결
  src/api/accountsAPI.ts
  src/api/emailsAPI.ts
  src/api/hooks/clients/usePostSetClient.ts
  src/api/hooks/emails/usePostSendEmail.ts
  src/api/hooks/reports/usePatchReportLogo.ts
  src/api/hooks/reports/usePostReportArticle.ts
  src/api/keywordsAPI.ts
  src/api/reportsAPI.ts
  src/api/tokenInstance.ts
  src/api/types/emails.ts
  src/api/types/reports.ts
  src/assets/svgs/dashboard.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/notFound.svg
  src/components/SideMenu/index.tsx
  src/constants/category.ts
  src/constants/clientId.ts
  src/features/report/ArticleTable/SortableItem.tsx
  src/features/report/ArticleTable/index.tsx
  src/features/report/ReportHeader/index.tsx
  src/features/report/ReportSection/index.tsx
  src/features/report/ReportTables/index.tsx
  src/features/report/SendEmailModal/index.tsx
  src/features/report/SummarizeModal/index.tsx
  src/features/report/Table/index.tsx
  src/pages/Dashboard/components/AddModal/Step2/index.tsx
  src/pages/Dashboard/components/MonitoringCard/index.tsx
  src/pages/Dashboard/index.tsx
  src/pages/FindPassword/PasswordSentModal/index.tsx
  src/pages/FindPassword/index.tsx
  src/pages/Monitoring/components/Pagination/index.tsx
  src/pages/Monitoring/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/Report/ReportBox/index.tsx
  src/pages/Report/index.tsx
  src/pages/ReportEdit/components/AddArticleForm/index.tsx
  src/pages/ReportEdit/components/ReportEditSection/ColorPicker.tsx
  src/pages/ReportEdit/components/ReportEditSection/LogoUploader.tsx
  src/pages/ReportEdit/components/ReportEditSection/TitleEditor.tsx
  src/pages/ReportEdit/components/ReportEditSection/index.tsx
  src/pages/ReportEdit/index.tsx
Labels: Feat ✨, Refactor ♻️

#67 [Feature/#64] 고객사 조회 api 연결 및 로딩 처리 구현
  src/api/clientsAPI.ts
  src/api/hooks/clients/usePostSearchClient.ts
  src/api/types/clients.ts
  src/pages/Dashboard/components/AddModal/Step3/index.tsx
  src/pages/Dashboard/components/AddModal/index.tsx
  src/pages/Dashboard/index.tsx
Labels: Feat ✨, Style 💄

#71 [Refactor/#70] Client 이미지 업로드 엔드포인트 수정
  src/App.tsx
  src/api/clientsAPI.ts
  src/api/emailsAPI.ts
  src/api/hooks/clients/useDeleteClient.ts
  src/api/hooks/clients/usePostClient.ts
  src/api/hooks/clients/usePutClient.ts
  src/api/hooks/emails/useGetEmails.ts
  src/api/hooks/emails/usePutEmails.ts
  src/api/reportsAPI.ts
  src/api/tokenInstance.ts
  src/api/types/clients.ts
  src/api/types/emails.ts
  src/api/types/reports.ts
  src/components/SideMenu/index.tsx
  src/constants/routes.ts
  src/features/report/ArticleTable/index.tsx
  src/features/report/SendEmailModal/index.tsx
  src/features/setting/KeywordList/index.tsx
  src/features/setting/TabNavigation/index.tsx
  src/pages/Dashboard/components/AddModal/index.tsx
  src/pages/Dashboard/components/DeleteModal/index.tsx
  src/pages/Dashboard/components/EditModal/index.tsx
  src/pages/ReportNew/components/ReportSection/LogoUploader.tsx
  src/pages/Setting/index.tsx
  src/pages/SettingEmail/MailTab/index.tsx
  src/pages/SettingEmail/index.tsx
  src/pages/SettingKeyword/SearchKeywordsTab/index.tsx
  src/pages/SettingKeyword/index.tsx
  src/router.tsx
Labels: Refactor ♻️

#73 [Feature/#68] 랜딩 페이지 구현 및 푸터 구현
  package-lock.json
  package.json
  src/assets/images/clientManagement.webp
  src/assets/images/copyright.webp
  src/assets/images/function1.webp
  src/assets/images/function2.webp
  src/assets/images/function3.webp
  src/assets/images/index.tsx
  src/assets/images/insights.webp
  src/assets/images/output.webp
  src/assets/images/performance.webp
  src/assets/images/testimonials.webp
  src/assets/svgs/arrowNextFill.svg
  src/assets/svgs/barChart.svg
  src/assets/svgs/blog.svg
  src/assets/svgs/clock.svg
  src/assets/svgs/grayLogo.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/instagram.svg
  src/assets/svgs/lightBulb.svg
  src/assets/svgs/unlimited.svg
  src/assets/svgs/youtube.svg
  src/components/Footer/index.tsx
  src/pages/Landing/components/Badge/index.tsx
  src/pages/Landing/index.tsx
  src/pages/Monitoring/components/ArticleBox/index.tsx
  src/pages/Report/ReportBox/index.tsx
  src/pages/ReportNew/components/AddNews/index.tsx
  src/router.tsx
  tailwind.config.js
Labels: Feat ✨

#75 [Feature/#72] 보고서 편집 페이지 api 연결
  src/api/articlesAPI.ts
  src/api/hooks/articles/useGetArticles.ts
  src/api/hooks/articles/useGetArticlesByKeyword.ts
  src/api/hooks/reports/useDeleteReportArticleCategory.ts
  src/api/hooks/reports/useGetReportArticlesOptions.ts
  src/api/hooks/reports/useGetReportCategories.ts
  src/api/hooks/reports/usePatchReportArticleCategory.ts
  src/api/hooks/reports/usePatchReportArticlesOptions.ts
  src/api/hooks/reports/usePostReportArticleCategory.ts
  src/api/reportsAPI.ts
  src/api/types/articles.ts
  src/api/types/reports.ts
  src/components/Input/index.tsx
  src/features/report/ArticleTable/CategoryAddModal.tsx
  src/features/report/ArticleTable/CategorySelectModal.tsx
  src/features/report/ArticleTable/SortableItem.tsx
  src/features/report/ArticleTable/index.tsx
  src/features/report/DonerMenu/index.tsx
  src/features/report/SummarizeModal/index.tsx
  src/pages/Monitoring/index.tsx
  src/pages/ReportEdit/components/AddArticleForm/index.tsx
  src/pages/ReportEdit/components/ReportEditSection/index.tsx
Labels: Feat ✨

#80 [Refactor/#74] 대시보드 및 키워드 설정 페이지 리팩토링
  src/api/hooks/emails/usePutEmails.ts
  src/pages/Dashboard/components/AddModal/index.tsx
  src/pages/Dashboard/components/EditModal/index.tsx
  src/pages/Dashboard/index.tsx
  src/pages/SettingEmail/index.tsx
  src/pages/SettingKeyword/index.tsx
Labels: Feat ✨, Refactor ♻️

#84 [Style/#83] 랜딩페이지 스타일 수정
  src/assets/svgs/grayLogo.svg
  src/components/Footer/index.tsx
  src/pages/Landing/index.tsx
  tailwind.config.js
Labels: Style 💄

#85 [Refactor/#82] 고객사 모달 리팩토링 및 기타 스타일 수정
  src/assets/images/function3.webp
  src/assets/svgs/arrowNextFill.svg
  src/components/KeywordInput/index.tsx
  src/features/setting/TabNavigation/index.tsx
  src/pages/Dashboard/components/AddModal/components/Step2/index.tsx
  src/pages/Dashboard/components/ClientNotFound/index.tsx
  src/pages/Dashboard/index.tsx
  src/pages/Landing/index.tsx
  src/pages/SettingKeyword/index.tsx
Labels: Refactor ♻️, Style 💄
