Repository The-Monitor-Dev/The-Monitor-FE, pull requests merged in 2024-10, with the labels that each got.

#2 Feature/#1
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/_layout.tsx
  src/assets/svg/checkBoxFill.svg
  src/assets/svg/checkboxBlank.svg
  src/assets/svg/checkboxError.svg
  src/assets/svg/index.tsx
  src/assets/svg/logo.svg
  src/assets/svg/visibilityOff.svg
  src/assets/svg/visibilityOn.svg
  src/components/Header/index.tsx
  src/components/test/index.tsx
  src/constants/routes.ts
  src/main.tsx
  src/pages/Main/index.tsx
  src/pages/SignIn/index.tsx
  src/router.tsx
  src/routes.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: Chore 🧹, Feat 🩵

#4 [Feature/#3] 인풋 컴포넌트 구현 및 적용
  package-lock.json
  package.json
  src/components/Input/index.tsx
  src/pages/SignIn/index.tsx
Labels: Feat 🩵

#6 [Feature/#5] 버튼 컴포넌트 구현 및 적용
  src/components/Button/index.tsx
  src/pages/SignIn/index.tsx
Labels: Feat 🩵

#8 [Feature/#7] 회원가입 폼
  src/assets/svg/error.svg
  src/assets/svg/index.tsx
  src/components/Input/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/components/Step1/PasswordCondtion.tsx
  src/pages/SignUp/components/Step1/index.tsx
  src/pages/SignUp/components/Step2/index.tsx
  src/pages/SignUp/index.tsx
Labels: Add ✨, Feat 🩵

#11 [Feature/#10] 로그인 페이지 퍼블리싱
  README.md
  src/components/Button/index.tsx
  src/constants/routes.ts
  src/pages/FindPassword/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/components/Step1/index.tsx
  src/pages/SignUp/components/Step2/index.tsx
  src/pages/SignUp/index.tsx
  src/router.tsx
Labels: Docs 📄, Feat 🩵, Refactor ♻️

#13 [Feature/#12] 비밀번호 찾기 페이지 퍼블리싱
  README.md
  commitlint.config.cjs
  src/components/Input/index.tsx
  src/pages/FindPassword/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/components/Step1/index.tsx
  src/pages/SignUp/components/Step2/index.tsx
Labels: Docs 📄, Feat 🩵, Refactor ♻️

#17 [Bugfix/#16] svg 파일 이름 수정
  src/assets/svg/checkboxFill.svg
Labels: Fix 🛠️

#19 [Chore/#18] Vercel.json 파일 생성
  vercel.json
Labels: Chore 🧹

#20 [Feature/#15] 회원가입, 로그인 API 연결
  .gitignore
  README.md
  src/App.tsx
  src/api/accountsAPI.ts
  src/api/apiUtils.ts
  src/api/axiosInstance.ts
  src/api/hooks/accounts/usePostSendEmailConfirm.ts
  src/api/hooks/accounts/usePostSignIn.ts
  src/api/hooks/accounts/usePostSignUp.ts
  src/api/hooks/accounts/usePostVerifyCode.ts
  src/api/types.ts
  src/components/Input/index.tsx
  src/hooks/useCheckPasswordValidation.ts
  src/hooks/useEmailConfirmation.ts
  src/pages/FindPassword/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/components/Step1/PasswordCondition.tsx
  src/pages/SignUp/components/Step1/index.tsx
  src/pages/SignUp/index.tsx
  src/utils/formatTime.ts
  tsconfig.app.json
Labels: Feat 🩵, Refactor ♻️

#22 [Feature/#21] 비밀번호 찾기 페이지 완성
  package.json
  src/api/accountsAPI.ts
  src/api/apiUtils.ts
  src/api/hooks/accounts/usePostSendEmailConfirm.ts
  src/api/hooks/accounts/usePostSendPasswordChangeEmail.ts
  src/api/hooks/accounts/usePostSignIn.ts
  src/api/hooks/accounts/usePostSignUp.ts
  src/api/hooks/accounts/usePostVerifyCode.ts
  src/api/types/accounts.ts
  src/api/types/response.ts
  src/assets/svg/close.svg
  src/assets/svg/index.tsx
  src/assets/svg/loading.svg
  src/components/Button/index.tsx
  src/components/Input/index.tsx
  src/hooks/useEmailConfirmation.ts
  src/pages/FindPassword/components/PasswordSentModal/index.tsx
  src/pages/FindPassword/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/components/Step1/PasswordCondition.tsx
  src/pages/SignUp/components/Step1/index.tsx
  src/pages/SignUp/components/Step2/index.tsx
  tailwind.config.js
Labels: Add ✨, Chore 🧹, Feat 🩵, Refactor ♻️

#23 [Feature/#9] 대시보드 페이지 퍼블리싱
  src/assets/images/defaultImage.webp
  src/assets/images/index.tsx
  src/assets/svg/addCircleFill.svg
  src/assets/svg/delete.svg
  src/assets/svg/editSquare.svg
  src/assets/svg/index.tsx
  src/assets/svg/moreHoriz.svg
  src/assets/svg/person.svg
  src/assets/svg/search.svg
  src/constants/routes.ts
  src/pages/Dashboard/components/DeleteModal/index.tsx
  src/pages/Dashboard/index.tsx
  src/pages/FindPassword/components/PasswordSentModal/index.tsx
  src/router.tsx
  tailwind.config.js
Labels: Add ✨, Feat 🩵

#27 [Feature/#26] 로그인, 회원가입 버튼 및 로고 라우팅 기능 추가
  .husky/pre-commit
  package-lock.json
  package.json
  src/api/hooks/accounts/usePostSignIn.ts
  src/api/hooks/accounts/usePostSignUp.ts
  src/components/Button/index.tsx
  src/components/Header/index.tsx
  src/constants/routes.ts
  src/pages/FindPassword/components/PasswordSentModal/index.tsx
  src/pages/FindPassword/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/components/Step1/index.tsx
  src/pages/SignUp/components/Step2/index.tsx
  src/utils/cn.ts
Labels: Chore 🧹, Feat 🩵, Refactor ♻️
